### ISSUE TITLE
Development Checklist

### ISSUE THREAD

**Issue by michealharker** [caffeinery/coffea-irc#3]
- [ ] **configuration spec**
 - [ ] **connection to irc**
 - [ ] **pipe connection to parser**
 - [ ] **handling all of the following bi-directionally:**
     - [ ] message
         - [ ] _message intent support_
         - [ ] _notice_
     - [ ] join
          - [ ] _extended-join support_
     - [ ] part
     - [ ] quit
     - [ ] kick
     - [ ] ping
     - [ ] irc cap support (more used internally)
         - [ ] _cap sasl_
         - [ ] _cap extended-join_
         - [ ] _cap away-notify_
         - [ ] _cap account-notify_
     - [ ] away
     - [ ] motd
     - [ ] names
     - [ ] invite
     - [ ] mode
     - [ ] numeric
     - [ ] whois
     - [ ] nick
